### ISSUE TITLE
smartseq 1/2 support

### ISSUE THREAD

**Issue by matq007** [nf-core/scrnaseq#258]
### Description of feature

Hi, I would like to add smartseq and smartseq2 support to the pipeline. StarSolo [supports it](https://github.com/alexdobin/STAR/blob/master/docs/STARsolo.md#plate-based-smart-seq-scrna-seq) which means it's simple to adjust it. From quick night session it requires only 2 files to be changed.

- [nextflow_schema.json](https://github.com/nf-core/scrnaseq/blob/afcb5cf6ab1afaddb773e49ce1d19c024820cff1/nextflow_schema.json#L68)
- `modules/local/star_align.nf`

and by adding custom configuration

```
process {
    withName: STAR_ALIGN {
        ext.args = "--readFilesCommand zcat --soloUMIdedup Exact --soloStrand Unstranded"
    }
}
```

From my understanding this should be enough to make this work. I can implement and submit a PR.

**Comment by grst** [comment]
How would the samplesheet look like in this case? Since with smartseq every cell is sequenced independently, wouldn't this lead to one sample per cell in the end? We likely would need a different logic for merging biological samples in that case. 

In the past we have recommended to use the `rnaseq` pipeline for smart-seq2 data. Is there any reason why this doesn't work for you?

**Comment by nasjr08** [comment]
Is this now an option for this nfcore or is the recommendation still to use the bulk rnaseq nfcore?

**Comment by grst** [comment]
`rnaseq` is still the way to go for SmartSeq1/2.
