### ISSUE TITLE
Make scrnaseq pipeline v2.5.1 compatible with nextflow v22.04.0

### ISSUE THREAD

**Issue by asmaali98** [nf-core/scrnaseq#308]
### Description of feature

Hi, is there any way to make the **nf-core/scrnaseq v2.5.1** compatible with the **nextflow v22.04.0** by implementing any changes? Has anyone tried this before? Is there any script changes that I can add to make it compatible?

**Comment by grst** [comment]
Since the nf-core template version 2.9 Nextflow 23.04 is officially required. This was probably mostly due to introducing the `nf-validation` plugin which is not used by this pipeline yet. 

Have you tried just removing this line from the nextflow.config?
https://github.com/nf-core/scrnaseq/blob/90cb6a48155248286c85395c53a201c3a31b2258/nextflow.config#L274

We will, however, not try to support older versions of nextflow, therefore, I'm closing this ticket. If you need more help getting to run this on legacy systems, I think slack is the better place to ask for help.
