### ISSUE TITLE
Cellranger mkref resource flags incorrect

### ISSUE THREAD

**Issue by RPSeaman** [nf-core/scrnaseq#329]
### Description of the bug

Hey all, I am looking at the `cellranger mkref` module and noticed that automatic available resources detection has been added, but I think I have spotted an inconsistency in the flags used for memory and cores: 

In their docs (https://www.10xgenomics.com/support/software/cell-ranger/latest/resources/cr-command-line-arguments) they specify `--memgb` and `--nthreads` as the two flags for cpu and memory, not  `--localmem` and --`localcores` as specified in the module. 

![Screenshot 2024-05-13 at 3 33 42 PM](https://github.com/nf-core/scrnaseq/assets/76637624/8a3c3ac9-8a30-491f-bc60-15a903852ea0)

Let me know you further clarification is needed. 

### System information

nf-core/scrnaseq 2.6.0

**Comment by grst** [comment]
`--localmem` and `--localcore` are global options passed to the martian runtime (martian is actually a workflow manager similar to nextflow). They should apply to all cellranger tools that are based on martian and `mkref` was changed from a simple script to the martian runtime in the last release. 

https://www.10xgenomics.com/support/software/cell-ranger/latest/resources/cr-command-line-arguments

However, given the documentation you point at I'm wondering if we should *additionally* pass `--nthreads` because otherwise star index generation likely only runs on a single core which takes forever. 

If you could update the module on `nf-core/modules` that would be fantastic!

**Comment by grst** [comment]
Fixed in https://github.com/nf-core/modules/pull/6136

**Comment by grst** [comment]
fixed in dev
